name: ffmpeg_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  file_picker: ^5.0.0
#  ffmpeg_kit_flutter: ^6.0.3
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  video_player: ^2.4.6
  path_provider: ^2.0.11
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy.ttf
        - asset: assets/fonts/SourGummy_Italic.ttf
          style: italic

    - family: Momcake
      fonts:
        - asset: assets/fonts/MomcakeThin-9Y6aZ.otf
        - asset: assets/fonts/MomcakeBold-WyonA.otf
          weight: 700

    - family: Lemon Milk
      fonts:
        - asset: assets/fonts/LemonMilkMedium-mLZYV.otf
        - asset: assets/fonts/LemonMilkBold-gx2B3.otf
          weight: 700
        - asset: assets/fonts/LemonMilkMediumItalic-d95nl.otf
          style: italic

    - family: Forzan
      fonts:
        - asset: assets/fonts/ForzanLight-ALWAA.ttf

    - family: Salmapro
      fonts:
        - asset: assets/fonts/SalmaproMedium-yw9ad.otf

    - family: Good Unicorn
      fonts:
        - asset: assets/fonts/GoodUnicornRegular-Rxev.ttf

    - family: Blanks Script
      fonts:
        - asset: assets/fonts/BlanksscriptpersonaluseBdit-jEM6O.otf

    - family: Vergilia
      fonts:
        - asset: assets/fonts/Vergilia-mL6aa.ttf

    - family: Rantys
      fonts:
        - asset: assets/fonts/RantysFreeRegular-p7A0y.otf

    - family: Glutern Serif
      fonts:
        - asset: assets/fonts/GluternSerif-ZVv2z.otf

    - family: Vintage Postcard
      fonts:
        - asset: assets/fonts/VintagePostcard-z8XY3.ttf
        - asset: assets/fonts/VintagePostcardItalic-6YyOY.ttf
          style: italic

    - family: Beautiful Blossoms
      fonts:
        - asset: assets/fonts/BeautifulBlossoms-2OGlX.ttf

    - family: Vacation Postcard
      fonts:
        - asset: assets/fonts/VacationPostcardNf-gDnP.ttf
